spring.profiles.active=dev
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.application.name=springboot-course
langchain4j.open-ai.chat-model.model-name=gpt-4o-mini